### ISSUE TITLE
Import and export feature

### ISSUE THREAD

**Issue by daaru00** [herlon214/gdsc#5]
Hi,

is it possible to export service's configuration into a file and then import it into a different swarm? 

For example something like this:
```bash
gdsc --from my-service --export-to /home/docker/my-service.json
```
and then on an other host:
```bash
gdsc --export-from /home/docker-2/my-service.json --name my-service
```

**Comment by herlon214** [comment]
Hi @daaru00, this is not possible yet :cry: 

Feel free to submit pull requests.

**Comment by herlon214** [comment]
@daaru I’m working on it.

**Comment by daaru00** [comment]
Wow great, thank you! How does it work?

**Comment by herlon214** [comment]
@daaru00 checkout the new release `2.0.0` and see the README. You can run `gdsc import --help` and `gdsc export --help`
